# Generated by Django 5.2.4 on 2025-10-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vehicle', models.CharField(max_length=20)),
                ('speed', models.FloatField()),
                ('plate', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
