# Generated by Django 5.2.7 on 2025-10-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolation',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='speedviolation',
            name='plate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='speedviolation',
            name='vehicle',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
