# Generated by Django 5.2.7 on 2025-10-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_speedviolation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedviolation',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='detection.video'),
        ),
    ]
