# Generated by Django 5.2.7 on 2025-10-16 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_speedviolation_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speedviolation',
            name='frame_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speedviolation',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='detection.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
